### ISSUE TITLE
Primary forest

### ISSUE THREAD

**Issue by fchichorro** [USEPA/fedelemflowlist#196]
Could we have a flowable named `Primary forest` (kg), or with a similar name (`Wood, primary forest`)? It is an important flowable for the CED method, for instance, where it is the sole contributor to the category `Non-renewable, biomass`. Same units as "Wood" but as a non-renewable resource.

Having this flowable would also allow a better mapping against Ecoinvent, as this flow exists there in the form of `Wood, primary forest, standing` (m3)

**Comment by bl-young** [comment]
hi @fchichorro - yes I think this would make sense. I'll note that we have had a FEDEFL adapted CED Method for a while [here](https://www.lcacommons.gov/lca-collaboration/National_Renewable_Energy_Laboratory/CED_Method/datasets), which also includes a primary forest flow that was not officially a FEDEFL flow. This method is being added to the LCIAfmt for consistency.
