### ISSUE TITLE
Adding new toxic organic flows to the FEDEFL

### ISSUE THREAD

**Issue by bnjmnmorelli** [USEPA/fedelemflowlist#202]
Attached is a list of toxic organics that I propose adding to the FEDEFL.

[New FEDEFL Flows.csv](https://github.com/user-attachments/files/17639880/New.FEDEFL.Flows.csv)

I propose using the IUPAC chemical name as the main FEDEFL flowable name (labeled TargetFlowName in attached). The SourceFlowNames could be included as synonyms.

**Comment by bl-young** [comment]
@bnjmnmorelli any suggestions for external references for these flows?
