### ISSUE TITLE
NEI Nitrogen Oxides mapped to Nitrogen dioxide

### ISSUE THREAD

**Issue by m-jamieson** [USEPA/fedelemflowlist#43]
I was surprised to find this mapping - is it intentional? As in, is there some reason that entities reporting NOx to NEI are actually reporting NO2?

**Comment by WesIngwersen** [comment]
I believe it was an assumption that NOx is primarily comprised of NO2 and the interest in making sure it is characterized, where factors for NOx are missing from some categories where factors for NO2 are present @hottleta @ashleyedelen
